Upgrade dependency for `async-nats` for `nats-server`.
Without this change during Cargo sync step, the following error is produced:
```
\nats.rs\nats-server> cargo.exe check --workspace --all-targets --features async-nats/default,async-nats/ring,async-nats/server_2_10,async-nats/server_2_11,async-nats/server_2_12,async-nats/service --keep-going
error: failed to select a version for `async-nats`.
    ... required by package `nats-server v0.1.0 (\nats.rs\nats-server)`
    ... which satisfies path dependency `nats-server` (locked to 0.1.0) of package `nats v0.25.0 (\nats.rs\nats)`
versions that meet the requirements `^0.38` (locked to 0.38.0) are: 0.38.0

package `nats-server` depends on `async-nats` with feature `server_2_11` but `async-nats` does not have that feature.
 package `async-nats` does have feature `server_2_10`

failed to select a version for `async-nats` which could resolve this conflict
```

Also, enabled `nats-server` tests on Windows. I have checked and they are passing locally.